$ANSIBLE_VAULT;1.1;AES256
66303566333234623134333261353238343362313838656332653366383238326332613666666663
3662656461623162393362653637656130383439396233310a306439373666666565313264333033
32316464656135643834383537623432646633313463663334343334383136653335366130343339
6661613662646364300a303036363164333138313235653731646235393266653565363430613764
34663636346266633539613762336332333232353265626162656239363963376664346432316336
61346538623934653965383538643432643866663731343561643266646632643765393533613436
65623363653538343764356431326337643535303838303532393639303563393165393837316434
37623265353630323361343030363963346430633936303133666163643931303236323335396131
64663930373232323731303963323932613732616535376636353864636136306664623062333633
66613330323037346137336332353539663137353638326436656236353336616638346132393263
62623935616335306632653133633838656236333337323864376333393062636138303530363935
35363762656437353863373563363737316539326263666139353364353164646630323433623964
64393163323338303230303630393539303333643036306639623234663462353737
