---
# Sesuaikan user default CentOS kamu (biasanya 'root' atau 'centos')
ansible_user: endiaz
ansible_port: 22

# Password (Gunakan Vault kayak tadi biar aman, atau plaintext sementara buat tes)
ansible_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          35626662633662353035366339343864623761613364376337366330653235336337623661643338
          3037303437623866306166343335376237363233623330330a656338323232636634303965653665
          32643564646538336630323361653834333761323234616530323665663461326330363635373362
          6134623238353438630a326363356165646166333239343239666565623464663638633432633134
          32316233336236373435653731653436653632663364353138343162336466316334

ansible_become_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          35626662633662353035366339343864623761613364376337366330653235336337623661643338
          3037303437623866306166343335376237363233623330330a656338323232636634303965653665
          32643564646538336630323361653834333761323234616530323665663461326330363635373362
          6134623238353438630a326363356165646166333239343239666565623464663638633432633134
          32316233336236373435653731653436653632663364353138343162336466316334


# INI PENTING BUAT SERVER BARU:
# Biar Ansible gak nanya "Are you sure..." (Auto Accept Fingerprint)
ansible_ssh_common_args: '-o StrictHostKeyChecking=no'