ansible_become_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          65613464303162393864353862613339633434336237373639613136623063663265633138343763
          3835373735313162616164383937616265663739623937320a626238643333363838643765313864
          38393564636666346638656338666530653030656432393061636433396161643531383566613934
          3434383264373964390a663666373265323563616166326239656337316364383831653036393230
          3434
