ansible_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          35636338323631633732636432623732393733313961326133303135646361313435346230633330
          6334376564623666303830366334363035363464613532390a316562613565306532663831333839
          62303935323162666336313230363232333866633132333030363131356538333466623032393130
          3039653065383966320a356539333537323032326463326130323161393131326364396361386232
          3036
