---
ansible_user: endiaz
ansible_port: 22
ansible_python_interpreter: /usr/bin/python3.12
ansible_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          64313735653237366264326666393934653061343466656531653239313431666332656431373165
          3062386633333137613231666231666430346364643965350a623863343166386234323731643635
          36363339353937373465653363633338646238323462383137346661626534313831356363646530
          3365363665643832650a633137353063376230623238383934643834613830363639303433303233
          38393132653630303637623031663531666337366636353236383535363830653261