ansible_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          64636434623230646164336534373834626662623261353635373335653662386430386239356332
          3466303531623239326435623538653965623965636265370a653137383064363261303762613934
          34323262363762623033303936316538333030323934636465386130336466376538303265656632
          6335306163323233630a306535303533643332626133343464313732653161613033653562326637
          6136
