ansible_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          64613261633734626566356436356332313562653635656465623135633134393737613763633331
          6635646630303664356262653539383166336333633163650a663932353930363934636136393161
          37623238356562393363393366666536663931343232656337663433646332303234393065633266
          3266656537306363330a323537343438343438383061643530353730383939346164313662363163
          6438
