ansible_become_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          36376265363663346530633930633136633461383962363132346630393034663437616365666464
          3235636561663638646436376532396337336566656366640a366139343031376665383061353266
          30643232336632363934623764393166363535313764373933653765353336663961333564343530
          3938336265653232640a313733636332643536633033353864386163316266343137653866383039
          6366
